[tool.poetry]
name = "alpaca-py"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7.0"
black = "^22.1.0"
isort = "^5.10.1"
requests = "^2.27.1"
furo = "^2022.2.14"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
