name: Run Tests and other CI Steps

on: [push, pull_request]

jobs:
  tests-ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8] #we'll want to add other versions down the road
        poetry-version: [1.1.13]
        os: [ubuntu-latest] #in the future we should add windows here
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Poetry install and run tests
        run: poetry install && poetry run pytest
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Poetry install and run tests
        run: poetry install && poetry run black --check alpaca/ tests/
